Added checks for missing but necessary files

diff --git a/src/shell/runheadless b/src/shell/runheadless
--- a/src/shell/runheadless
+++ b/src/shell/runheadless
@@ -5,13 +5,27 @@
 
 # Assume that src/NetLogo.jar is a link to the real NetLogo.jar.
 netlogo=~/bali/src/NetLogo.jar
-# netlogo="/Applications/NetLogo 5.1.0/NetLogo.jar"
-
 datadir=$HOME/bali/data
 
-if [ -z "$1" ]; then
-	echo "usage: $0 <experimentname> [subdirname] [ additional-netlogo-args ]"
+function usage () {
+	echo "usage: $0 <BehviorSpaceExperiment> [subdirname] [ additional-netlogo-args ]" >&2
+	echo "BehviorSpaceExperiment: The name of a BehaviorSpace experiment defined in BaliPlus.nlogo" >&2
+	echo "subdirname: Name of subdirectory of $datadir.  If missing, put data in $datadir." >&2
+}
+
+if [ ! -r "$netlogo" ]; then 
+	echo "NetLogo jar file '$netlogo' is missing or unreadable."
 	exit 1
+fi
+
+if [ ! -r "$datadir" ]; then 
+	echo "Data directory '$datadir' is missing."
+	exit 2
+fi
+
+if [ -z "$1" ]; then
+	usage
+	exit 3
 fi
 
 experiment="$1"
